Resources:
     mys3bucketfortesting:
       Type: AWS::S3::Bucket
       Properties:
         Tags:
            - Key: Name
              Value: mydemos3-bucket-iac
            - Key: Owner
              Value: admin@try-devops.xyz
            - Key: IaC
              Value: CloudFormation
